// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { envConfig } from "./config/env-config";
const { engine, host, port, user, password, dbName } = envConfig.db;

// Prisma mysql
// DATABASE_URL="mysql://root:password@localhost:3306/nextapp"

const databaseUrl = `${engine}://${user}:${password}@${host}:${port}/${dbName}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
